config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :short_urls, only: [:create]
  get '/:short_code/show', to: 'short_urls#show', as: "short_url"
  get '/:short_code/statistic', to: 'short_urls#statistic', as: 'short_urls_statistic'
  get '/:short_code', to: 'short_urls#redirect'
  get "*path", to: "application#render_404"
  
  # Defines the root path route ("/")
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/short_url.rb
class ShortUrl < ApplicationRecord
    validates :short_code, presence: true, length: { minimum: 6 }, uniqueness: true, on: :create
    validates :target_url, presence: true, format: URI::DEFAULT_PARSER.make_regexp(%w[http https])
    validates :title_tag, presence: true
    validates :clicks, presence: true, numericality: { greater_than_or_equal_to: 0 }
    has_many :visits
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :short_url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def render_404
        render file: "#{Rails.root}/public/404.html", status: :not_found
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def index
        @short_url = ShortUrl.new
    end

end

app/controllers/short_urls_controller.rb
require 'securerandom'
require 'open-uri'
require 'nokogiri'

class ShortUrlsController < ApplicationController

    def create
        @short_url = ShortUrl.new(short_url_params)

        if @short_url.validate(:target_url)
            @short_url.target_url = @short_url.target_url.gsub(/[[:space:]]/, '') 
            @short_url.short_code = generate_short_code
            
            title_tag = generate_title_tag(@short_url.target_url)
            if title_tag.present?
                @short_url.title_tag = title_tag
            end

            @short_url.save
            redirect_to short_url_path(@short_url.short_code)
        else
            render "pages/index", status: :unprocessable_entity
        end
    end

    def new
        @short_url = ShortUrl.new
    end

    def show
        @short_url = ShortUrl.find_by(short_code: params[:short_code])
        if !@short_url.present?
            render_404
        end
    end     

    def statistic
        @short_url = ShortUrl.find_by(short_code: params[:short_code])
        if !@short_url.present?
            render_404
        end
    end
    
    def redirect
        begin
            @short_url = ShortUrl.find_by(short_code: params[:short_code])
            @short_url.increment(:clicks).save
            @short_url.visits.create(originating_geolocation: generate_originating_geolocation)
            redirect_to @short_url.target_url, allow_other_host: true
        rescue
            render_404
        end
    end

    private      
        def generate_short_code()
            short_code = SecureRandom.hex(3)[0, 15]

            # Check if the short code is already taken
            while ShortUrl.find_by(short_code: short_code).present?
                short_code = SecureRandom.hex(3)[0, 15]
            end

            return short_code
        end

        def generate_title_tag(target_url)
            begin
                html = URI.open(target_url)
                doc = Nokogiri::HTML(html)
                title_node_set = doc.css('title')
                return title_node_set.empty? ? nil : title_node_set.text
            rescue
                return nil
            end
        end

        def generate_originating_geolocation
            ip_address = request.remote_ip == "127.0.0.1" ? "172.56.21.89" : request.remote_ip
            results = Geocoder.search(ip_address).first
            return "#{results.city}, #{results.country}"
        end   

        def short_url_params
            params.require(:short_url).permit(:target_url, :short_code)
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>URL Shortener | Top URL Shortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <script src="https://cdn.tailwindcss.com"></script>
    <%= favicon_link_tag asset_path('logo.png') %>
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/index.html.erb
<div class="flex h-screen">
    <div class="m-auto text-center w-4/5">
        <h1 class="text-4xl font-bold mb-1">URL Shortener</h1>
        <p class="mb-6">It's much simpler to share a shorter link than a long and complicated one.</p>
        <%= render "short_urls/new" %>
    </div>    
</div>

app/views/short_urls/_new.html.erb
<%= form_with model: @short_url, url: short_urls_path, class: "max-w-lg m-auto" do |form| %>
    <div class="flex items-center justify-between border-b border-black py-2 m-auto">
        <%= form.text_field :target_url, name: 'short_url[target_url]', 
        placeholder: "Enter the link here", 
        class: "w-full mr-3 py-1 px-2 focus:outline-none text-gray-700" 
        %>
        <%= form.submit "Shortern", class: "cursor-pointer" %>
    </div>
    <% if @short_url.errors.full_messages.any? %>
        <% @short_url.errors.full_messages.each do |error_message| %>
            <% if @short_url.errors.full_messages.first == error_message %>
                <p class="text-left mt-1  text-red-500">
                    <i class="fa-solid fa-triangle-exclamation px-2"></i><%= error_message %>
                </p>
            <% end %>
        <% end %>
    <% end %>
<% end %>

app/views/short_urls/show.html.erb
<div class="flex h-screen">
    <div class="m-auto w-4/5 max-w-2xl">

        <div class="text-center">
            <h1 class="text-4xl font-bold mb-2">Voila! Your shortened link</h1>
            <p>Copy the shortened link and share it in messages, texts, posts, websites and other locations.</p>
            <%= link_to "Shorten another link", root_path, class: "text-blue-600 hover:underline" %>
        </div>
        
        <div class="my-10">
            <div class="mb-6">
                <h2 class="text-xl font-bold mb-1">Short Link</h2>
                <%= link_to "#{request.protocol}#{request.host_with_port}/#{@short_url['short_code']}", 
                            "/#{@short_url['short_code']}", 
                            data: {turbo: false},
                            target: "_blank", 
                            class: "break-all text-blue-600 hover:underline" %>
                <p>
                    <i class="fa-regular fa-lightbulb"></i> 
                    Check out how your short link is doing with the 
                    <%= link_to "statistic", 
                                short_urls_statistic_path(@short_url.short_code), 
                                class: "text-blue-600 hover:underline" %>.
                </p>
            </div>
            <div class="mb-6">
                <h2 class="text-xl font-bold mb-1">Original Link</h2>
                <%= link_to @short_url['target_url'], 
                            @short_url['target_url'], 
                            target: "_blank",
                            class: "break-all text-blue-600 hover:underline" %>
            </div>
            <div class="mb-6">
                <h2 class="text-xl font-bold mb-1">Page Title</h2>
                <%= @short_url['title_tag'] %></span>
            </div>
        </div>        

    </div>    
</div>

app/views/short_urls/statistic.html.erb
<div class="flex h-screen">
    <div class="m-auto w-4/5 max-w-2xl">

        <%= link_to "Back", short_url_path(@short_url.short_code), class: "text-blue-600 hover:underline" %>
        <div class="text-center mt-2">
            <h1 class="text-4xl font-bold mb-1">Statistics</h1>
            <p>Discover how your short link: 
                <%= link_to "#{request.protocol}#{request.host_with_port}/#{@short_url['short_code']}", 
                            "/#{@short_url['short_code']}", 
                            data: {turbo: false}, 
                            target: "_blank",
                            class: "break-all text-blue-600 hover:underline" %> 
                is doing in real-time!
            </p>
            <div class="my-10">
                <h2 class="text-lg">Number of Clicks</h2>
                <p class="text-3xl font-bold mb-1"><%= @short_url['clicks'] %></p>
            </div>
        </div>
        
        <% if @short_url.visits.size > 0 %>
        <h2 class="text-xl font-bold mb-1">Recent Visits</h2>
        <table class="border border-gray-400 border-collapse w-full text-center">
            <thead class="bg-gray-200">
                <tr>
                <th class="py-2 px-4">Geolocation</th>
                <th class="py-2 px-4">Timestamp</th>
                </tr>
            </thead>
            <tbody>
                <% @short_url.visits.order(created_at: :desc).each do |short_url| %>
                <tr>
                    <td class="py-2 px-4"><%= short_url.originating_geolocation %></td>
                    <td class="py-2 px-4"><%= short_url.created_at %></td>
                </tr>
                <% end %>
            </tbody>
        </table>
        <% elsif @short_url.visits.size == 0 %>
        <h2 class="text-xl font-bold mb-1 text-center">No one has visited this short link yet.</h2>
        <% end %>
    </div>
</div>